networks:
  productionanalysis-dev:
    driver: bridge

services:
  productionanalysis.api:
    container_name: productionanalysis.api
    image: productionanalysis.api
    build:
      context: .
      dockerfile: ProductionAnalysis.Api/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONTAINER: "productionanalysis.db"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - productionanalysis.db
      
  productionanalysis.db:
    container_name: productionanalysis.db
    image: postgres:18.0
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: